### ISSUE TITLE
Bug in util_alloc_realpath__

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#239]
I think this function has a bug. If you feed it something like: `a/b/c/../c/../..` (yes I know, a beautiful path). You will get `a/b` back, while you would expect `a`.

Basically you create a gap of false entries with the first `c/..`, then the `while(!mask[prev_index])` brings you past this gap when hitting the second `c`. Then the `../..` starts going backwards marking path elements as false, that are already false. I think it should either be implemented with a stack or the similar functionality of "fast forwarding" backwards to find a true entry should be implemented.

**Comment by joakim-hove** [comment]
Should be fixed in #232

**Comment by markusdregi** [comment]
Seems to have been resolved.
