### ISSUE TITLE
Remove util

### ISSUE THREAD

**Issue by pgdr** [equinor/libecl#290]
Remove from ecl
* `ArgPack`,
* `CThreadPool`, in progress: Statoil/libecl#311 + Statoil/libres#230
* `Bool/PermutationVector`,
* ~~`Buffer`,~~ (Statoil/libecl#291)
* `CWDContext`,
* `Hash`, https://github.com/Statoil/libecl/pull/323
* `LookupTable`,
* ~~`Matrix/polyfit` in progress: Statoil/libecl#335 + Statoil/libres#231~~
* ~~`PathFormat`,~~ (Statoil/libecl#292)
* ~~`Profiler`~~ : https://github.com/Statoil/libecl/pull/314
* `RandomNumberGenerator`,
* `util_func.py`
* `util_spawn` → move to res
* ~~`util_ping`~~ → move to res, or preferably delete https://github.com/Statoil/libres/pull/234 + #320 
* ~~Remove Functions: `util_read_path( )`~~ : https://github.com/Statoil/libecl/pull/321
* Remove `thread_pool`

**Comment by joakim-hove** [comment]
Yes - I agree that we should strive to remove not really relevant utility code from libecl. The code which is listed above is probably a good starting point. As I see it the code can be divided in several categories:

##### 1: Totally unused
This should just be removed.

##### 2: Not used in libecl, but used in libres
This should be moved to the `libres-util` library. 

##### 3: Code where the C implementation is used internally in libecl, and the Python interface is used in libres. Unclear what to do with this?

##### 4: Code where the C implementation is used internally in libecl, but the Python wrapper is not used at all. 

C code remains, python wrappers removed?

##### 5: numpy stuff.

Uncertain about the matrix / polyfit stuff. The matrix is certainly needed in libres, but can maybe just be moved there. The numpy dependency in libecl is very limited - maybe it would be a good idea to start a more extensive use of numpy?

I will get back to this issue and group the different files after how they should be treated. 

PR's with code-change are welcome!

**Comment by markusdregi** [comment]
I'll close this one due to lack of momentum
