### ISSUE TITLE
Create ACTNUM EclKW from PORV

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libecl#338]
The most natural way to infer information about/inactive cells is from the Grid, but it can also be inferred from the `PORV` keyword in the INIT file - where `PORV` has value 0 for inactive cells. The purpose of this issue is to be able to create a ACTNUM `EclKW` from a `PORV` keyword - quite simple stuff, but it should be fast.

**Comment by pgdr** [comment]
I thought that it wasn't an iff between actnum and PORV==0.  Have I been wrong?

I can set a cell with PORV>0 to be inactive, can't I?

**Comment by joakim-hove** [comment]
> I can set a cell with PORV>0 to be inactive, can't I?

yes - you can; but when Eclipse (and flow for that matter) writes an INIT file in that case it will explicitly write 0.0 for the PORV value - i.e. the interaction is twoways.

**Comment by magnesj** [comment]
This issue can be closed
