### ISSUE TITLE
Access of nullptr in well_state causes crash

### ISSUE THREAD

**Issue by magnesj** [equinor/libecl#413]
## Description
When reading simulation wells nullpointer access is detected in well_state.cpp : well_state_add_LGR_connections

https://github.com/Statoil/libecl/blob/10401dd964d59d33ff6a5f5978ef11cfc7d64646/lib/ecl/well_state.cpp#L449

## Suggested action
Do nothing if lgr_view is null

**Comment by joakim-hove** [comment]
OK - thank you; fix is here: #414 - but if you could in addition send me the EGRID and UNRST files in question, so that we can make a test-case for this, that would be good.

**Comment by hhgs** [comment]
File location sent per email.

**Comment by magnesj** [comment]
@joakim-hove Do you have a progress update on this issue?

**Comment by joakim-hove** [comment]
It is not forgotten, but it has fallen a bit off the wagon yes.
