### ISSUE TITLE
Ubuntu Kill Signal on loading EGRID file using EclGrid

### ISSUE THREAD

**Issue by tpradeep** [equinor/libecl#446]
EGRID is around 1.5 GB. On Mac I don't see any error but it freezes in
between. Loading using EclFile works fine.

*ERROR:*
```
Error message: Program received signal:11

See file: /tmp/ert_abort_dump.pradeep.20180805-024425.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
Aborted (core dumped)
```

*LOG:*

```
Abort called from: util_abort_signal (libecl/lib/util/util.c:4652)

Error message: Program received signal:11
```

```
--------------------------------------------------------------------------------
 #00 util_abort__(..)             in /usr/include/x86_64-linux-gnu/bits/stdio2.h:97
 #01 ????
 #02 ???(..)                      in libecl/lib/ecl/ecl_grid.c:2951
 #03 ecl_grid_alloc_EGRID(..)     in libecl/lib/ecl/ecl_grid.c:2970
 #04 ecl_grid_load_case__(..)     in libecl/lib/ecl/ecl_grid.c:3716
 #05 ffi_call_unix64(..)          in ???
 #06 ffi_call(..)                 in ???
 #07 _ctypes_callproc(..)         in ???
 #08 ????
 #09 PyObject_Call(..)            in ???
 #10 PyEval_EvalFrameEx(..)       in ???
 #11 PyEval_EvalCodeEx(..)        in ???
 #12 ????
 #13 ????
 #14 PyObject_Call(..)            in ???
 #15 ????
 #16 PyEval_EvalFrameEx(..)       in ???
 #17 PyEval_EvalCodeEx(..)        in ???
 #18 ????
 #19 ????
 #20 ????
 #21 ????
 #22 PyEval_EvalFrameEx(..)       in ???
 #23 PyEval_EvalCodeEx(..)        in ???
 #24 ????
 #25 PyRun_FileExFlags(..)        in ???
 #26 PyRun_SimpleFileExFlags(..)  in ???
 #27 Py_Main(..)                  in ???
 #28 __libc_start_main(..)        in ???
 #29 _start(..)                   in ???
--------------------------------------------------------------------------------
```

**Comment by joakim-hove** [comment]
Hello;

thank you for the bug report. Unfortunately it is not immediately clear from the backtrace what the problem might be. I can see from the backtrace (the .c extension) that your libecl distribution is not entirely new - could you download the current master and try again. Not that I think that will solve anything - but then we can get a more precise/usable backtrace.

**Comment by tpradeep** [comment]
I downloaded the new files using git clone https://github.com/Statoil/libecl.git
Error message: Program received signal:11

See file: /tmp/ert_abort_dump.pradeep.20180805-175800.log for more details of the crash.
Setting the environment variable "ERT_SHOW_BACKTRACE" will show the backtrace on stderr.
Aborted (core dumped)
---------------------------------------------------------------------------------------------

Abort called from: util_abort_signal (/home/pradeep/Documents/libecl/lib/util/util.c:4478) 

Error message: Program received signal:11



--------------------------------------------------------------------------------
 #00 util_abort__(..)                                                              in /usr/include/x86_64-linux-gnu/bits/stdio2.h:97
 #01 ???? 
 #02 ???(..)                                                                       in /home/pradeep/Documents/libecl/lib/ecl/ecl_grid.cpp:3031
 #03 ecl_grid_alloc_EGRID(..)                                                      in /home/pradeep/Documents/libecl/lib/ecl/ecl_grid.cpp:3050
 #04 ecl_grid_load_case__(..)                                                      in /home/pradeep/Documents/libecl/lib/ecl/ecl_grid.cpp:3796
 #05 ffi_call_unix64(..)                                                           in ???
 #06 ffi_call(..)                                                                  in ???
 #07 _ctypes_callproc(..)                                                          in ???
 #08 ???? 
 #09 PyObject_Call(..)                                                             in ???
 #10 PyEval_EvalFrameEx(..)                                                        in ???
 #11 PyEval_EvalCodeEx(..)                                                         in ???
 #12 ???? 
 #13 ???? 
 #14 PyObject_Call(..)                                                             in ???
 #15 ???? 
 #16 PyEval_EvalFrameEx(..)                                                        in ???
 #17 PyEval_EvalCodeEx(..)                                                         in ???
 #18 ???? 
 #19 ???? 
 #20 ???? 
 #21 ???? 
 #22 PyEval_EvalFrameEx(..)                                                        in ???
 #23 PyEval_EvalCodeEx(..)                                                         in ???
 #24 ???? 
 #25 PyRun_FileExFlags(..)                                                         in ???
 #26 PyRun_SimpleFileExFlags(..)                                                   in ???
 #27 Py_Main(..)                                                                   in ???
 #28 __libc_start_main(..)                                                         in ???
 #29 _start(..)                                                                    in ???
--------------------------------------------------------------------------------

**Comment by tpradeep** [comment]
The file is generated by Eclipse. I had tried importing the file in ResInsight. That crashed too. I can upload EGRID to google drive and share the link with your email address (Can't share it in public)

**Comment by joakim-hove** [comment]
Thank you for the updated backtrace.

Cool if you share the model, my email is joakim.hove - Gmail.

**Comment by markusdregi** [comment]
Closed due to inactivity. If the problem persists, feel free to open a new issue.
