### ISSUE TITLE
Add deprecgitation warnings in ecl.ecl and ert.ecl packages.

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libecl#528]
The documentation: #527 must be completed first.

When this task is completed it should be backported to a 2.3-Warning version which can be used by selected users, before eventually (probably) being fully backported to the 2.3 version.

**Comment by markusdregi** [comment]
How to do this was explored in: https://github.com/Statoil/libecl/pull/393/files, https://github.com/Statoil/libecl/pull/394,

**Comment by markusdregi** [comment]
Will not be resolved
