### ISSUE TITLE
compilation fails under windows at make stage

### ISSUE THREAD

**Issue by trhallam** [equinor/libecl#532]
Hi,

I've been trying to compile this package under a windows ecosystem following the guide in Windows.txt. I have tried a few versions of MingGW and now MSYS2 but I consistently encounter the following errors during the compilations stage.

I've also tried using release 2.3.1 instead of the master branch. 

Any help would be greatly appreciated.

Cheers
Tony

`make\n
Scanning dependencies of target catch2

[  0%] Building CXX object external/catch2/CMakeFiles/catch2.dir/dummy.cpp.obj
[  1%] Linking CXX shared library ../../lib/libcatch2.dll
[  1%] Built target catch2
Scanning dependencies of target ecl
[  2%] Building CXX object lib/CMakeFiles/ecl.dir/util/rng.cpp.obj
[  3%] Building CXX object lib/CMakeFiles/ecl.dir/util/lookup_table.cpp.obj
[  4%] Building CXX object lib/CMakeFiles/ecl.dir/util/statistics.cpp.obj
[  5%] Building CXX object lib/CMakeFiles/ecl.dir/util/mzran.cpp.obj
[  6%] Building CXX object lib/CMakeFiles/ecl.dir/util/hash_node.cpp.obj
[  7%] Building CXX object lib/CMakeFiles/ecl.dir/util/hash_sll.cpp.obj
[  8%] Building CXX object lib/CMakeFiles/ecl.dir/util/path.cpp.obj
[  9%] Building CXX object lib/CMakeFiles/ecl.dir/util/hash.cpp.obj
[ 10%] Building CXX object lib/CMakeFiles/ecl.dir/util/node_data.cpp.obj
[ 11%] Building CXX object lib/CMakeFiles/ecl.dir/util/node_ctype.cpp.obj
[ 12%] Building C object lib/CMakeFiles/ecl.dir/util/util.c.obj
c:/dev/libecl-2.3.1/lib/util/util.c: In function 'util_copy_file__':
c:/dev/libecl-2.3.1/lib/util/util.c:1950:26: warning: passing argument 2 of 'stat' from incompatible pointer type [-Wincompatible-pointer-types]
         stat( src_file , &stat_buffer );
                          ^~~~~~~~~~~~
In file included from c:/dev/libecl-2.3.1/lib/util/util.c:47:
c:/msys64/mingw64/x86_64-w64-mingw32/include/sys/stat.h:185:53: note: expected 'struct stat *' but argument is of type 'stat_type *' {aka 'struct _stat64 *'}
 int __cdecl stat(const char *_Filename,struct stat *_Stat);
                                        ~~~~~~~~~~~~~^~~~~
c:/dev/libecl-2.3.1/lib/util/util.c: At top level:
c:/dev/libecl-2.3.1/lib/util/util.c:2155:6: error: conflicting types for 'util_access'
 bool util_access(const char * entry, int mode) {
      ^~~~~~~~~~~
In file included from c:/dev/libecl-2.3.1/lib/util/util.c:91:
C:/dev/libecl-2.3.1/lib/include/ert/util/util.h:359:16: note: previous declaration of 'util_access' was here
   bool         util_access(const char * entry, mode_t mode);
                ^~~~~~~~~~~
c:/dev/libecl-2.3.1/lib/util/util.c: In function 'util_mkdir':
c:/dev/libecl-2.3.1/lib/util/util.c:4624:10: error: too many arguments to function 'mkdir'
   return mkdir( path , UTIL_DEFAULT_MKDIR_MODE );
          ^~~~~
In file included from c:/dev/libecl-2.3.1/lib/util/util.c:78:
c:/msys64/mingw64/x86_64-w64-mingw32/include/direct.h:59:15: note: declared here
   int __cdecl mkdir(const char *_Path) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
               ^~~~~
c:/dev/libecl-2.3.1/lib/util/util.c: At top level:
c:/dev/libecl-2.3.1/lib/util/util.c:4870:5: error: redefinition of 'util_chdir'
 int util_chdir(const char * path) {
     ^~~~~~~~~~
c:/dev/libecl-2.3.1/lib/util/util.c:4862:5: note: previous definition of 'util_chdir' was here
 int util_chdir(const char * path) {
     ^~~~~~~~~~
make[2]: *** [lib/CMakeFiles/ecl.dir/util/util.c.obj] Error 1
make[1]: *** [lib/CMakeFiles/ecl.dir/all] Error 2
make: *** [all] Error 2`

**Comment by joakim-hove** [comment]
Thank you for the interest - will look into it. See the `.appveoyor` file for how it is built on Windows.

I am sorry to say that the Windows.txt file is very outdated.

**Comment by trhallam** [comment]
Thanks Joakim,

I am really keen to get this working with Python under windows and l did
not see the appveoyor file. Also, my apologies as I suspect this would all
be much easier under a Linux umbrella.

I tried again to compile using VS 2017. The initial cmake build completes
but notifies me of many missing functions, 'fork' for example. I also have
installed cwrap using pip and it raises an error about not finding that
either.

Finally the build progresses but fails on a function related to getting the
git version.

In all this I am thinking that my env and path variables might not quite be
right. I'm going to set up a shell for VS2015, python 2.7 and try again.

If I can get this working, would you be interested in me updating
Windows.txt?

Cheers Tony

**Comment by trhallam** [comment]
Hi Joakim, 

Just updating the status of this thread. 

I believe I have compiled the code by setting up the right environment and running
`cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DERT_BUILD_CXX=OFF -DBUILD_APPLICATIONS=ON ..`
and 
`cmake --build . --config Release --target install`

similar to the appveoyer instructions. There are just two warnings:
`c:\dev\libecl-2.3.1\lib\util\ecl_version.cpp(9): error C2561: 'ecl_version_get_git_commit': function must return a va lue [C:\dev\libecl-2.3.1\build\lib\ecl.vcxproj]
  c:\dev\libecl-2.3.1\lib\util\ecl_version.cpp(17): error C2561: 'ecl_version_get_git_commit_short': function must retu rn a value [C:\dev\libecl-2.3.1\build\lib\ecl.vcxproj]`

From that I don't quite know where the install ends up but I have a set of python bindings that I can import from _/lib/python2.7/site-packages_ . This results in error relating to a missing _dlopen()_ module.  In the readme you add an install folder called _lib64_ to the LD_LIBRARY_PATH but I don't appear to get any directories of that nature after running the two build commands.

Thanks again
Tony

**Comment by stefoss23** [comment]
The two functions does return value in any case, but that is decided my macros. Setting something like 'return NULL' at the end might force your specific compiler setup to accept it.

**Comment by trhallam** [comment]
> 
> 
> The two functions does return value in any case, but that is decided my macros. Setting something like 'return NULL' at the end might force your specific compiler setup to accept it.

Happy days! I had to replace the git functions completely with a `return "blah";` but the compilation completed and the binaries were built. 

I tested them no problem.
`
C:\dev\libecl-2.3.1\build\bin\Release
λ grid_info.exe "C:\dev\libecl-2.3.1\test-data\local\ECLIPSE\faarikaal\faarikaal1.EGRID"
      Name ..................: C:\dev\libecl-2.3.1\test-data\local\ECLIPSE\faarikaal\faarikaal1.EGRID
      Grid nr ...............: 0
      Active cells ..........: 4160
      Active fracture cells..: 0
      nx ....................: 7
      ny ....................: 6
      nz ....................: 169
      Volume ................: 7098
      Origo X................:  463393.91
      Origo Y................: 7338619.50
`
However, with the link to python I still receive an error about dlopen()
`
dlopen() error: [Error 126] The specified module could not be found
`
I added the build folder containing catch2.dll, ecl.exp, ecl.lib and libecl.dll to the system path before receiving this error.

Cheers
Tony

**Comment by trhallam** [comment]
Thanks for your help, the last error was due to importing modules from ecl in an odd way. The examples within _docs/examples_ for loading data in python seem to be out of date?

My final compile was with MS VS 2017 and Python 3.6.7

**Comment by joakim-hove** [comment]
Thank you for your perseverance - I am very pleased you got it through. If you want to submit updates of your experiences we will merge that.

Your point about example / documentation is of course correct ... ;-(

**Comment by trhallam** [comment]
I'll try to summarise the workflow in the near future. Looking forward to using this for sim2seis.

Cheers

**Comment by trhallam** [comment]
Solved this the other day. If you don't have the git support files in the folder structure it throws this error because it doesn't know how to work out the git version. I can recreate this error by deleting git tracking folders from the source directory. For example:
```
cd libecl
rm -rf *.git
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\dev\ERT\test\ -DBUILD_SHARED_LIBS="ON" -DENABLE_PYTHON="ON"  -DERT_BUILD_CXX="ON" -DBUILD_APPLICATIONS="ON" ..\.
cmake --build . --config Release

"C:\dev\source\libecl_nogit\build\install.vcxproj" (default target) (1) ->                                  
"C:\dev\source\libecl_nogit\build\ALL_BUILD.vcxproj" (default target) (3) ->                                
"C:\dev\source\libecl_nogit\build\applications\CF_dump.vcxproj" (default target) (4) ->                     
"C:\dev\source\libecl_nogit\build\lib\ecl.vcxproj" (default target) (5) ->                                  
(ClCompile target) ->                                                                                       
  c:\dev\source\libecl_nogit\lib\util\ecl_version.cpp(9): error C2561: 'ecl_version_get_git_commit': functi 
on must return a value [C:\dev\source\libecl_nogit\build\lib\ecl.vcxproj]                                   
  c:\dev\source\libecl_nogit\lib\util\ecl_version.cpp(17): error C2561: 'ecl_version_get_git_commit_short': 
 function must return a value [C:\dev\source\libecl_nogit\build\lib\ecl.vcxproj]                            
                                                                                                            
    524 Warning(s)                                                                                          
    2 Error(s)                                                                                              
```

Discovered this when I downloaded the release ZIP file the other day and couldn't compile again because there was no git tracking in the extracted source directory.
