### ISSUE TITLE
Remove warning when building with Python 3

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/libecl#542]
When building ecl against Python 3, a few warnings are displayed while running CMake. Those warning are bogus, `libecl` works fine even with Python 3

**Comment by markusdregi** [comment]
Especially with Python 3.6. Perhaps we should have a discussion regarding which Python 3 versions we should support and then have Travis run tests on all of them..? And then only generate warnings if you are not using one of the "approved" Python versions..
