### ISSUE TITLE
Pip install support

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#545]
Something was started here: https://github.com/Statoil/libecl/pull/264

There is also some not very well tested support for this already in the repo.

**Comment by xjules** [comment]
I will make a try with multibuild (also remove it as a submodule and get it cloned solely to travis)

**Comment by andreabrambilla** [comment]
Work initiated by @xjules on https://github.com/equinor/libecl/pull/580 but temporarily put on hold

**Comment by dotfloat** [comment]
Closing due to #691 .
