### ISSUE TITLE
Aborts if mixed case is used in datafile name

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#582]
Eclise does not handle mixed case in filenames, while Intersect does. Libecl tests for mixed case, which might not make sense as we are only to read the data anyway. Should we remove these guards?

Could you pinpoint the relevant code @lars-petter-hauge?

**Comment by lars-petter-hauge** [comment]
There might be more; but at least here https://github.com/equinor/libecl/lib/ecl/ecl_util.cpp#L37

**Comment by magnesj** [comment]
Several ResInsight users have been facing this issue, and is blocking for some users. Please allow input of data with mixed casing.

https://github.com/OPM/ResInsight/issues/4496

**Comment by markusdregi** [comment]
@magnesj Is this restricted to mixed casing or are there also other symbols used in the base names?

**Comment by magnesj** [comment]
So far we have seen reports only to mixing of case, not other symbols.
