### ISSUE TITLE
Documentation on read the docs

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#584]
Should we build `libecl` documentation on read the docs or similar solution?

**Comment by magnesj** [comment]
ResInsight is currently using Jekyll and GitHub Pages. All documentation is written in MarkDown, and we have done some adjustments to the coding of the website.
https://github.com/OPM/ResInsight/tree/gh-pages

The documentation is growing, and we are missing dynamic menus. We are currently considering two options:
1. Implement menus in Jekyll 
2. Move to a different page generator system. We are considering moving to https://gohugo.io/

**Comment by markusdregi** [comment]
Until the documentation building has matured a bit, we will be hosting the documentation internally. We will get back to open hosting later.

**Comment by magnesj** [comment]
As indicated earlyer, resinsight.org is now powered by Hugo https://gohugo.io/

https://github.com/OPM/ResInsight-UserDocumentation

**Comment by markusdregi** [comment]
Thank you for your input @magnesj :+1:
