### ISSUE TITLE
Summary : Access of invalid data when reading summary file

### ISSUE THREAD

**Issue by magnesj** [equinor/libecl#591]
**Description**
This file has been used as part of ResInsight User Course, and causes crash in libecl

libecl tries to access data out of bounds, and crashes with abort.

1. Load the attached summary file into ResInsight
2. Open a summary plot
3. Selecet type Well, and select well **OP_6**
4. Select **WBHP** -> ResInsight crashes

File causing this crash
[3_R001_REEK-1.ZIP](https://github.com/equinor/libecl/files/2995641/3_R001_REEK-1.ZIP)

See workaround in ResInsight
https://github.com/OPM/ResInsight/commit/e1d842d3a41de44c2d05982877c6ce388539f471

**General remark**
libecl crashes when error situations occur. As an end user application as ResInsight, the preferred behaviour is to show an error message. It should be possible to instruct libecl to report errors when they occur, and return gracefully if this is possible.

**Comment by joakim-hove** [comment]
The zip file is missing the data part - i.e. `3_R001_REEK-1.UNSMRY`. Can you point to the code in Resinsight which is at the top of the call stack - my hunch is that you are asking for a vector which is not present in the data; that will fail hard - but there are query functions you can call first to check.

**Comment by magnesj** [comment]
Sorry, the zip file is now updated with the missing file. We do ask for available vectors before asking for data, I think this is an internal issue in libecl.

**Comment by joakim-hove** [comment]
OK; I repeat that it would be valuable to see the callsite in Resinsight.

**Comment by magnesj** [comment]
![image](https://user-images.githubusercontent.com/1793152/54812801-4fd4f680-4c8c-11e9-9383-34740381383b.png)

**Comment by joakim-hove** [comment]
Is this still on?

**Comment by magnesj** [comment]
I can test and get back to you.

**Comment by magnesj** [comment]
Import of data from these test files causes issues in libecl v 2.4.0.

**Comment by joakim-hove** [comment]
Loading the file with the `summary.x` utility in the libecl distribution works fine -  so this is probably a slightly subtle bug, would be good if you could post an updated backtrace.
