### ISSUE TITLE
Well State : Crash when trying to read connection data for grid

### ISSUE THREAD

**Issue by magnesj** [equinor/libecl#598]
Changes in libecl has caused `well_state_iget_wellhead( const well_state_type * well_state , int grid_nr)` not to work with ResInsight.  

**Suggested fix**
Check the ranges for the vector, and return NULL if outside bounds.

https://github.com/equinor/libecl/commit/a0ea20afdd59c1725b4424af7764b9e9803e74bd#r32986299

**Comment by joakim-hove** [comment]
Fix here: https://github.com/equinor/libecl/pull/599
