### ISSUE TITLE
ecl_smspec_install_special_keys : Crash when well name is null pointer

### ISSUE THREAD

**Issue by magnesj** [equinor/libecl#602]
The attached summary files causes crash when using the summary.x tool for version 2.4.0
[summary_crash.zip](https://github.com/equinor/libecl/files/3033065/summary_crash.zip)

![image](https://user-images.githubusercontent.com/1793152/55389251-2db56100-5535-11e9-9a2b-3c3c10d472ee.png)

**Comment by magnesj** [comment]
Please note that the files in this issue are different to the files related to issues #591 #601 and #603 , and triggers other errors in libecl.

**Comment by magnesj** [comment]
@markusdregi @joakim-hove 

Testes with master today, this issue is not fixed. See my previous comment to this issue:
> Please note that the files in this issue are different to the files related to issues #591 #601 and #603 , and triggers other errors in libecl.

**Comment by joakim-hove** [comment]
Thank you for testing with `summary.x` that makes everything simpler

**Comment by joakim-hove** [comment]
I have confirmed the crash

**Comment by joakim-hove** [comment]
```diff
diff --git a/lib/ecl/smspec_node.cpp b/lib/ecl/smspec_node.cpp
index 032e1ff..2b56bf7 100644
--- a/lib/ecl/smspec_node.cpp
+++ b/lib/ecl/smspec_node.cpp
@@ -680,8 +680,14 @@ ecl_smspec_var_type smspec_node::valid_type(const char * keyword, const char * w
       var_type == ECL_SMSPEC_LOCAL_COMPLETION_VAR) {
     if (IS_DUMMY_WELL(wgname))
       return ECL_SMSPEC_INVALID_VAR;
-    else
-      return var_type;
+
+    if (!wgname)
+      return ECL_SMSPEC_INVALID_VAR;
+
+    if (strlen(wgname) == 0)
+      return ECL_SMSPEC_INVALID_VAR;
+
+    return var_type;
   }
 
   if (var_type == ECL_SMSPEC_COMPLETION_VAR || var_type == ECL_SMSPEC_SEGMENT_VAR) {
```
