### ISSUE TITLE
External ACTNUM : External values are combined with values from file

### ISSUE THREAD

**Issue by magnesj** [equinor/libecl#605]
When simulation data is exported from Intersect to EGRID, the ACTNUM data is not correct. When ResInsight tries to import exported data from **Intersect,** the **PORV** keyword is inspected, and ACTNUM is set to 1 for cells with PORV > 0.0. This ACTNUM data is passed to `ecl_grid_alloc_EGRID__` using the parameter `ext_actnum`. Inside this function, the externally specified ACTNUM is combined with file internally values (by multiplying external ACTNUM values with file values).

This behaviour is causing ResInsight not to be able to import data from Intersect. We want to be able to apply the externally specified ACTNUM without modifications.

This behaviour was introduced in https://github.com/equinor/libecl/pull/445

**Reference to code**
https://github.com/equinor/libecl/blob/5a62567956c3266faa2eb36b5cf7808bed9e1ce0/lib/ecl/ecl_grid.cpp#L3025-L3041

**Comment by joakim-hove** [comment]
This was implemented to support Intersect based import into Resinsight - it was implemented a bit in the blind, with feedback coming now I think this should be changed.

**Comment by joakim-hove** [comment]
Before a PR is made - can you please confirm that the number of elements in the solution vectors -e.g. `PRESSURE` and `SWAT` agrees with the number of 1 values in the `ext_actnum`?
