### ISSUE TITLE
Unmappable characters for encoding UTF-8 in atomic.h

### ISSUE THREAD

**Issue by matteodg** [equinor/libecl#618]
The file `lib/include/ert/util/atomic.h` contains some unmappable characters for encoding UTF-8.
I'll create a pull request to fix this.

**Comment by joakim-hove** [comment]
Cool - try to create a PR removing the file completely - I do not think it is in use.

**Comment by matteodg** [comment]
Oh wow, so fast you guys: I just created a PR with the fix on the offending chars. In case I'll change it to delete the file altogether.
