### ISSUE TITLE
Dual Porosity Regression

### ISSUE THREAD

**Issue by lindkvis** [equinor/libecl#623]
In the last ResInsight upgrade of libECL we are no longer receiving all the fracture results in a dual porosity case.

In particular our call to:
int fractureActiveIndex = ecl_grid_get_active_fracture_index1(localEclGrid, gridLocalCellIndex);
returns -1 for all cell indices.

Previously it returned a valid index. The result is that we no longer get SWAT and SGAS.

The upgrade was from:
7f93730c08a4d981a4b738b42146d099977572ce 

To:

0e1e780fd6f18ce93119061e36a4fca9711bc020

**Comment by lindkvis** [comment]
[DUALPERM_TEST.zip](https://github.com/equinor/libecl/files/3223636/DUALPERM_TEST.zip)

**Comment by jokva** [comment]
It would be very helpful if you could take your test case [1] and setup and bisect between the two revision to pinpoint exactly which revision it is that broke it. That way, figuring out the error will be much easier.

[1] or, provide me with an actual runnable test with code.

**Comment by joakim-hove** [comment]
I have not looked at this in any detail; but if this is what I think it is close to a "planned regression". Out of the top of my head the situation is as follows:

1. The grid files typically have an ACTNUM property to indicate active/inactive cells. In the case of dual porosity models the ACTNUM value is interpreted as a bitmask: where 1 corresponds to active matrix (i.e. normal active) and 2 corresponds to an active fracture.

2. As a feature, to enable Intersect compatibility, the grid loader used in libecl can be used with an externally supplied ACTNUM; this will then typically only contain 0/1 and then things fail. The new feature was implememnted here: https://github.com/equinor/libecl/pull/445 (there might have been a later fixup PR to this as well).

My guess is that this "external actnum" function really can not be used with dual porosity models - at least not yet.

**Comment by lindkvis** [comment]
@joakim-hove Thanks for a detailed reply! @magnesj thinks this makes sense and has some ideas for how to fix this on the ResInsight side. I'll close this issue now and open a ResInsight issue instead. Cheers!
