### ISSUE TITLE
Install libecl in python 3.6

### ISSUE THREAD

**Issue by GibranAlfa** [equinor/libecl#638]
Hi,

Can I install libecl package in python 3.6? If so, how do I do that? Thanks!

**Comment by andreabrambilla** [comment]
libecl is python 3 compatible, there should be no difference in building for python 2 and python 3. Did you get any error?

**Comment by GibranAlfa** [comment]
I already installed libecl in python 2.7, and when I switched to python 3 it said
![image](https://user-images.githubusercontent.com/52709954/61026881-fb799200-a3b4-11e9-9384-ebb867f3dd78.png)
Do you know how to fix this? Thanks!

**Comment by andreabrambilla** [comment]
it looks like `cwrap` is not installed, try `pip install cwrap`

**Comment by GibranAlfa** [comment]
okay that solves the problem, thanks!
