### ISSUE TITLE
release branch 2019.04 is missing.

### ISSUE THREAD

**Issue by dr-robertk** [equinor/libecl#641]
The correcponding branch for the OPM release 2019.04 (or at least a tag) is missing. Could that be created?

**Comment by jokva** [comment]
What release is that?

**Comment by dr-robertk** [comment]
The OPM 2019.04 release that depends on libecl. The tags or branches for the other, previous, releases also exist.

**Comment by jokva** [comment]
I mean what libecl release do you depend on, that you feel isn't there?

**Comment by dr-robertk** [comment]
Maybe I'll rephrase the question. Which libecl branch, tag, or commit should be used to build the OPM release 2019.04 from source?  I was hoping there was a tag or branch, but that does not exist for 2019.04, but it exists for 2018.10, 2018.04 and 2017.07. It currently work with libecl master but at some point that will break.

**Comment by markusdregi** [comment]
@jokva @dr-robertk Allow me to fill in here. _libecl_ have been released using semantic versioning for quite some years. In addition, @joakim-hove have been making calendar versions corresponding to the OPM releases. However, it is the semantic versions who have been receiving the most care, getting bug fixes by default etc. It is also the version that has been deployed internally in Equinor for various applications (besides OPM).

I would argue that the best thing for you to do would be to use the newest version of `2.4` (currently `2.4.1`) and move along when new micro releases are released. If not, you would have to carefully select a commit, in a similar manner as Joakim has done previously and ask if Jørgen is willing to tag it. I think it would be easier and better for all of us if you instead use the semantic versions.

**Comment by jokva** [comment]
> Maybe I'll rephrase the question. Which libecl branch, tag, or commit should be used to build the OPM release 2019.04 from source? I was hoping there was a tag or branch, but that does not exist for 2019.04, but it exists for 2018.10, 2018.04 and 2017.07. It currently work with libecl master but at some point that will break.

I don't know? I guess that depends on whatever opm actually uses. Joakim might be able to answer that.

In my opinion, libecl calendar releases aren't a good idea because no attention will be paid to them, and you should target the other tagged releases.

**Comment by dr-robertk** [comment]
I have to admit that I didn't want to start a big discussion about what type of release versioning should be used etc.I guess version 2.4.1 will just work fine.

**Comment by markusdregi** [comment]
Perfect 👍
