### ISSUE TITLE
How to get well location

### ISSUE THREAD

**Issue by sogoogos** [equinor/libecl#643]
Hello, 
What is the easiest way to get wellhead coordinates in the Python API?

**Comment by joakim-hove** [comment]
```python
from ecl.grid import EclGrid
from ecl.file import EclFile
from ecl.well import WellInfo

grid = EclGrid("CASE.GRID")
rst_file = EclFile("CASE.UNRST")

# Load *all* the information about all wells
well_info = WellInfo(grid, rst_file = rst_file)

# Extract the timeseries of information for one well
well_ts = well_info["MY-WELL"]

# Get the state of the well at report step 0
w0 = well_ts[0]

# Wellhead
head = w0.wellHead()
```

**Comment by sogoogos** [comment]
Thank you so much! Is there any comprehensive documentation for this library?

**Comment by markusdregi** [comment]
@sogoogos We have it on our short list of things to get done. I'll let you know when it is done :+1:

**Comment by markusdregi** [comment]
@sogoogos Until we have hosting resolved, you can always toogle on `RST_DOCS` while building and hence get the documentation built locally.
