### ISSUE TITLE
Problems compiling on Windows

### ISSUE THREAD

**Issue by Krijoher** [equinor/libecl#658]
I have tried compiling this library on windows several times now with cmake as refferred to in the documentation and other issues here. But I always get 2 errormessages related to a keyword.cpp file: 
"C:\temp\libecl\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\temp\libecl\build\ecl3\lib\ecl3-tests.vcxproj" (default target) (7) ->
(ClCompile target) ->
  c:\temp\libecl\ecl3\lib\tests\keyword.cpp(612): error C2146: syntax error: missing ')' before identifier 'and' [C:\temp\libecl\build\ecl3\lib\ecl3-tests.vcxproj]
  c:\temp\libecl\ecl3\lib\tests\keyword.cpp(612): error C2146: syntax error: missing '(' before identifier 'and' [C:\temp\libecl\build\ecl3\lib\ecl3-tests.vcxproj]

The commands I am using is: 
- git clone https://github.com/equinor/libecl
- cd libecl
- mkdir build
- cd build
- cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\dev\ERT\test\ -DBUILD_SHARED_LIBS="ON" -DENABLE_PYTHON="ON"  -DERT_BUILD_CXX="ON" -DBUILD_APPLICATIONS="ON" ..\.
- cmake --build . --config Release

My environment is:
- Windows 10
- cmake version 3.12.18081601-MSVC_2
- Visual Studio 2017

**Comment by Krijoher** [comment]
... and: 
- Python 3.7

**Comment by markusdregi** [comment]
Dear @Krijoher.

We have now removed some experimental and abandoned code that seemed to be the cause you problems: https://github.com/equinor/libecl/pull/661.

I suggest that you make a clean master and try again.

**Comment by Krijoher** [comment]
The master compiles just fine now, thanks a lot!
