### ISSUE TITLE
Disable "util abort on everything" for python 3

### ISSUE THREAD

**Issue by ManInFez** [equinor/libecl#694]
The flag ECL_SKIP_SIGNAL determines weither util_abort is called on sig-abort. There should also be a check weither python 2 or 3 is used. If python 3 -> dont use util abort

**Comment by dotfloat** [comment]
https://github.com/equinor/libecl/blob/08c4bb8ca3dfbe4f258675c0ebd6feee75b43eca/python/ecl/__init__.py#L140-L143

Note that `res` also tries to set the signals the same way `ecl` does:
https://github.com/equinor/libres/blob/6df5572b0166220d03059a3afff78f732f2ccf6d/python/res/__init__.py#L104-L106

As such, I propose to add the py3/2 test in this file:
https://github.com/equinor/libecl/blob/08c4bb8ca3dfbe4f258675c0ebd6feee75b43eca/python/ecl/util/util/install_abort_signals.py

And also remove the `install_signals` and `update_signals` cwrap functions from public view.
