### ISSUE TITLE
Move Jenkins job to scout

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#695]
The current jenkins job is running on the be-instance (https://ci.equinor.com/be/job/scout/job/libecl-pr). Jenkins script should be moved to GitHub and job moved to the scout instance. A new job was started here: https://ci.equinor.com/scout/job/libecl-pr/

**Comment by ManInFez** [comment]
is now taken over by https://ci.equinor.com/scout/job/komodo/job/libecl-pr/
