### ISSUE TITLE
Run libecl against komodo distributions

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#696]
Run libecl tests against komodo deploys `bleeding`, `unstable`, `testing` and `stable` (py2) and (py3) every night on the scout instance. Use the PR-job as a basis.

**Comment by sondreso** [comment]
Now we run the test every time we build a release, do we need to run it every night then? 
Only reason to do so is if we expect the release to change after deploy :)

**Comment by markusdregi** [comment]
Good point! I guess the only exception is `bleeding`?

**Comment by sondreso** [comment]
Test runs after bleeding is built also :tada:

**Comment by sondreso** [comment]
So they technically run every night

**Comment by ManInFez** [comment]
Will be solved when this connects to the release building pipeline:

https://github.com/equinor/komodo-releases/issues/205

**Comment by markusdregi** [comment]
Duplicate of other issues
