### ISSUE TITLE
cmake error: could not load cache

### ISSUE THREAD

**Issue by Gacaar** [equinor/libecl#702]
I'm using WLS running Ubuntu inside Windows 10 and trying to use ecl_summary to plot well curves simulated with flow (according to [OPM project's first tutorial](https://opm-project.org/?page_id=197&page=5) libecl should already be installed, since I have flow, but I can't find it).

I'm trying to follow Alternative 3 step-by-step to install libecl and set the BUILD_ECL_SUMMARY switch to on in the CMake configuration (according to [OPM project's wiki](https://wiki.opm-project.org/index.php?title=Main_Page#Text_based_solution:_ecl_summary) this is necessary to get the ecl_summary application).

When I run the command
`cmake libecl -DENABLE_PYTHON=ON -DBUILD_ECL_SUMMARY=ON`
`cmake --build libecl --target install`
I get the error:
`Error: could not load cache`

I'm running everything from the root folder.

**Comment by markusdregi** [comment]
Hi @Gacaar and thanks for testing `libecl`.

I don't think the Flow simulator depends on `libecl` any longer and hence you can't expect it to be in your environment. Instead, you will have to install it yourself. I'm certain the OPM community will appreciate a GitHub issue regarding their outdated tutorials ;)

Regarding your issues with building we'll get back to you later today.

**Comment by dotfloat** [comment]
There is a mistake in the README. Please use a previous version until we can get this fixed: https://github.com/equinor/libecl/blob/075b1f8d4d6d848f0d47180054b43e98cf61393d/README.md
