### ISSUE TITLE
Pip installation, no matching distribution found.

### ISSUE THREAD

**Issue by MitchPetersen** [equinor/libecl#709]
Hi there!

I've been trying for a while to install libecl 2.9.0, both on windows and a linux vm. 

I haven't been able to get the pip installation to work at this point. 

> pip install libecl
ERROR: Could not find a version that satisfies the requirement libecl (from versions: none)
ERROR: No matching distribution found for libecl

**Comment by markusdregi** [comment]
Hi @MitchPetersen!

Which version of Python are you using?

Cheers

**Comment by MitchPetersen** [comment]
Hey @markusdregi, I've been using a couple versions to test, the last one I tried on both Ubuntu and on Windows 10 was Python 3.6

**Comment by markusdregi** [comment]
Hmm, that is really odd! Do you manage to install other packages from PyPI?

**Comment by markusdregi** [comment]
It could also be that your pip is too old. Could you check the version of it?

**Comment by MitchPetersen** [comment]
Yep, things like pandas, matplotlib, lasio, etc, I was able to install. This has been the only case where I've run into this issue as of yet.

I'm currently using pip 20.1.

**Comment by markusdregi** [comment]
Hmm 🤔 Pip 20.1 works fine locally on my machine at least...

**Comment by markusdregi** [comment]
Are you installing libecl into a virtual env or something else?

**Comment by MitchPetersen** [comment]
I've tried into a virtual env through cmd, as well as pycharm. I then tried straight into the default installation on both windows and linux. All of the above encounter the same 'No Matching Distribution Found' error.

**Comment by dotfloat** [comment]
*libecl* is only available on Linux with Python 2.7, 3.6, 3.7 and 3.8 on a CentOS 6-compatible distribution (Ubuntu 18.04 and 20.04 fit the bill) and make sure pip is up-to-date in whichever environment you're running. It is **not** available on Windows.

Which version of Ubuntu are you using?

**Comment by MitchPetersen** [comment]
Ubuntu 18.04.3 is the version my VM is running on

**Comment by dotfloat** [comment]
What is the output of `pip --version` and `python --version`?

**Comment by MitchPetersen** [comment]
Well. Don't I look stupid. I thought I had upgraded pip as soon as I got the VM running. Turns out I was wrong. Sorry to waste your time, appreciate the help.

**Comment by markusdregi** [comment]
Happy you figured it out 👏

**Comment by dotfloat** [comment]
Time is meant to be wasted. :smile:

Wish I could make `pip` write something more user-friendly than "no matching distribution found", but alas.
