### ISSUE TITLE
Deploy to PyPI as `ecl` rather than `libecl`

### ISSUE THREAD

**Issue by dotfloat** [equinor/libecl#710]
We're currently deploying this package as `libecl` when we should probably deploy it as `ecl` since we own that name. We want to use `ecl` because it has the same name as the module. There are several ways to do this, and I'd say only 2 decent ones:

1. Deploy to `ecl`, make `libecl` be a dummy package with a high version number that depends only on `ecl` and prints a deprecation warning when installed.
2. Ditto, but keep `ecl` and `libecl` at the same version just in case.
3. (Bad) deploy to both `ecl` and `libecl`. There'll be confusion about which one is which, and they'd override each other when installed, leading to major problems.

The 2. point can be done with making generating the `libecl` wheel at the `before_deploy` step of Travis.

**Comment by pgdr** [comment]
I'm voting for 2.

**Comment by markusdregi** [comment]
I'm also voting for 2
