### ISSUE TITLE
Dual Porosity Grid Properties

### ISSUE THREAD

**Issue by tpradeep** [equinor/libecl#714]
I have the required files such as EGRID and INIT but due to dual porosity model, I have different number of Active grids and property values. How do I extract static grid properties such as porosity, permeability and dynamic properties for each grid in Python?

**Comment by joakim-hove** [comment]
> How do I extract static grid properties such as porosity, permeability and dynamic properties for each grid in Python?

I think they will just be in one long flat vector, with the matrix values first and the fracture values second; i.e. you will essentially have to implement the "divide in matrix and fracture" values in your application - something like:
```
grid = EclGrid("CASE.EGRID")
num_fracture = grid.get_num_active_fracture()
num_matrix = grid.get_num_active()

init_file = EclFile("CASE.INIT")
permx = init_file["PERMX"][0]
permx_matrix = permx[:num_matrix]
permx_fracture = permx[num_matrix:]
```

**Comment by tpradeep** [comment]
I tried this yesterday after posting the question. I wasn't sure if matrix values come first or fracture. Now it's clear and everything works great. Thanks
