### ISSUE TITLE
Conversion between binary and ascii grid file (.egrid ==> .grdecl)

### ISSUE THREAD

**Issue by ming-origen** [equinor/libecl#723]
Hi, I am pretty new to libecl. 
The grid files I have are in .egrid format, and I'm wondering how I can convert that into .grdecl format?
Would it be a simple conversion to ascii? What would be the base of the binary?
I am using the python binding.
Thanks!

**Comment by markusdregi** [comment]
Hi @ming-origen and thanks for showing interest in the `libecl` package. Have you tried loading the grid with the `EclGrid` class and then use the `save` functions available to store it again?

See:
- https://github.com/equinor/libecl/blob/69f1ee0ddf696c87b6d85eca37eed7e8b66ac2db/python/ecl/grid/ecl_grid.py#L236 and
- https://github.com/equinor/libecl/blob/69f1ee0ddf696c87b6d85eca37eed7e8b66ac2db/python/ecl/grid/ecl_grid.py#L1149

**Comment by ming-origen** [comment]
Hi @markusdregi,
Thank you for your help! This works 👍

**Comment by markusdregi** [comment]
Excellent! Have a good day 👍
